apiVersion: apps/v1
kind: Deployment
metadata:
  name: motivational-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motivational-app
  template:
    metadata:
      labels:
        app: motivational-app
    spec:
      containers:
      - name: motivational-app
        image: 548135082630.dkr.ecr.us-east-1.amazonaws.com/alaa-devops-project-app-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: motivational-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: motivational-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000