apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: "" 
    http:
      paths:
      - path: /nexus
        pathType: Prefix
        backend:
          service:
            name: nexus-sonatype-nexus
            port:
              number: 8081