apiVersion: v1
kind: Service
metadata:
  # Updated from temp-chart to motivational-app
  name: {{ include "motivational-app.fullname" . }}
  labels:
    {{- include "motivational-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}       # Port 80 (External)
      # Link to 5000 (Internal Flask Port)
      targetPort: {{ .Values.service.targetPort | default 5000 }} 
      protocol: TCP
      name: http
  selector:
    # Must match the labels in Deployment
    {{- include "motivational-app.selectorLabels" . | nindent 4 }}